[package]
name = "devtools-services"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
arboard.workspace = true
crossbeam-channel.workspace = true
global-hotkey.workspace = true
rdev.workspace = true
tokio.workspace = true
tray-icon.workspace = true
tracing.workspace = true
windows.workspace = true
