[package]
name = "devtools-storage"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
directories.workspace = true
rusqlite.workspace = true
sha2.workspace = true
time.workspace = true
tracing.workspace = true
