[package]
name = "devtools-plugin-host"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
devtools-plugin-api = { path = "../devtools-plugin-api" }
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
wasmtime.workspace = true
