use super::*;

/// 内置工具清单。默认文本使用英文，中文通过 i18n 字段提供。
pub fn builtin_commands() -> Vec<CommandDescriptor> {
    vec![
        command(
            "tool.json.format",
            "JSON Format",
            "Format and validate JSON text",
            "JSON 格式化",
            "格式化并校验 JSON 文本",
            vec!["json", "format", "pretty", "格式化"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.json.minify",
            "JSON Minify",
            "Compress JSON into one line",
            "JSON 压缩",
            "将 JSON 压缩为单行文本",
            vec!["json", "minify", "compress", "压缩"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.json.validate",
            "JSON Validate",
            "Check whether JSON text is valid",
            "JSON 校验",
            "检查 JSON 文本是否合法",
            vec!["json", "validate", "lint", "校验"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.base64.encode",
            "Base64 Encode",
            "Encode text as Base64",
            "Base64 编码",
            "将文本编码为 Base64",
            vec!["base64", "encode", "编码"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.base64.decode",
            "Base64 Decode",
            "Decode Base64 into text",
            "Base64 解码",
            "将 Base64 解码为文本",
            vec!["base64", "decode", "解码"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.uuid.v4",
            "UUID v4",
            "Generate a random UUID",
            "UUID v4",
            "生成随机 UUID",
            vec!["uuid", "guid", "random"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.jwt.decode",
            "JWT Decode",
            "Decode JWT header and payload without sending it online",
            "JWT 解析",
            "离线解析 JWT Header 与 Payload",
            vec!["jwt", "token", "decode", "解析"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.url.encode",
            "URL Encode",
            "Percent-encode text for a URL component",
            "URL 编码",
            "将文本进行 URL 百分号编码",
            vec!["url", "encode", "percent", "编码"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.url.decode",
            "URL Decode",
            "Decode URL percent-encoded text",
            "URL 解码",
            "解码 URL 百分号编码文本",
            vec!["url", "decode", "percent", "解码"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.timestamp.convert",
            "Timestamp Convert",
            "Convert Unix seconds or ISO 8601 time",
            "时间戳转换",
            "转换 Unix 秒级时间戳或 ISO 8601 时间",
            vec!["timestamp", "time", "unix", "date", "时间"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.uuid.generate",
            "UUID Generator",
            "Generate UUID v4 values; enter a count from 1 to 100",
            "UUID 批量生成",
            "生成 UUID v4；输入 1 到 100 的数量",
            vec!["uuid", "guid", "batch", "generate", "批量"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.uuid.normalize",
            "UUID Normalize",
            "Normalize UUID case and hyphens",
            "UUID 规范化",
            "规范 UUID 的大小写和横线",
            vec!["uuid", "guid", "uppercase", "lowercase", "横线"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.sql.format",
            "SQL Format",
            "Format common SQL clauses for readable output",
            "SQL 格式化",
            "格式化常见 SQL 子句",
            vec!["sql", "format", "query", "select", "格式化"],
            CommandSource::BuiltInTool,
        ),
        command(
            "tool.clipboard.history",
            "Clipboard History",
            "Browse and search local clipboard items",
            "剪贴板历史",
            "浏览和搜索本地剪贴板记录",
            vec!["clipboard", "history", "paste", "剪贴板"],
            CommandSource::BuiltInTool,
        ),
        command(
            "setting.theme",
            "Settings",
            "Theme and local data preferences",
            "设置",
            "主题、语言、快捷键与本地数据配置",
            vec!["settings", "theme", "preferences", "设置"],
            CommandSource::Setting,
        ),
    ]
}

/// 创建内置命令描述，统一补齐中文本地化和关键词。
pub(super) fn command(
    id: &str,
    title: &str,
    subtitle: &str,
    zh_title: &str,
    zh_subtitle: &str,
    keywords: Vec<&str>,
    source: CommandSource,
) -> CommandDescriptor {
    CommandDescriptor {
        id: id.into(),
        plugin_id: None,
        title: title.into(),
        subtitle: subtitle.into(),
        i18n: vec![CommandI18n {
            locale: "zh-CN".into(),
            title: zh_title.into(),
            subtitle: zh_subtitle.into(),
        }],
        keywords: keywords.into_iter().map(str::to_string).collect(),
        source,
    }
}
